name: startup_namer
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: kathyw <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: '>=3.0.0-alpha <4.0.0'
  angular2_components: '>=0.3.1-alpha <0.4.0'
  english_words: ^2.0.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
